PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE cardapio (data_da_semana text, prato_principal1 text, prato_principal2 text, prato_principal3 text, acompanhamento1 text, acompanhamento2 text, acompanhamento3 text,acompanhamento4 text, doce text, bebida1 text, bebida2 text, bebida3 text);
INSERT INTO cardapio VALUES('29/05/2023','Carne Imperial (isca de carne ao molho escuro com batatas em tiras salteados)','Coxa e sobrecoxa de frango assada ao creme de espinafre','Soja Imperial','Arroz amarelinho','Arroz integral refogado','Feijão Branco com macaxeira','Macarrão refogado','Laranja','Suco goiaba','Suco manga','Café');
INSERT INTO cardapio VALUES('30/05/2023','Friacassê de carne moída','Escondidinho de frango com purê de batata doce','Fricassê vegetariano','Arroz branco com cheiro verde','Arroz integral com cheiro verde','Baiao de dois com cheiro verde','Farofa de cuscuz ','Doce tipo mariola','Suco goiaba','Suco manga','Café');
INSERT INTO cardapio VALUES('31/05/2023','Carne cremosa (carne desfiada refogada ao molho branco com tiras de batata salteadas)','Estrogonofe de frango','Creme com verduras e legumes ao molho de leite de coco','Arroz branco amarelinho','Arroz integral com cheiro verde','Feijão Branco com cheiro verde','Farofa de mandioca','Melancia','Suco acerola','Suco caju','Café');
INSERT INTO cardapio VALUES('01/06/2023','Cubo suíno na chapa com refogado de cebola e pimentão e fatias de limão','Frango ao molho de milho (frango desfiado envolvido no creme de milho e com cheiro verde)','Escondidinho vegetariano ao molho de leite de coco com purê de batata doce','Arroz branco com cebolinha','Arroz integral com cebolinha','Feijão Branco com cheiro verde','Farofa de cuscuz','Doce tipo mariola','Suco goiaba','Suco manga','Café');
INSERT INTO cardapio VALUES('02/06/2023','Lasanha de carne a bolonhesa','Cubo de frango cozido ao molho de cebola cremoso e cheiro verde','Lasanha vegetariano com molho de leite de coco','Arroz branco com cheiro verde','Arroz integral com cheiro verde','Feijão branco com abóbora','Farofa de mandioca','Goiaba','Suco acerola','Suco caju','Café');
COMMIT;
